server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: "my-thread-"